<a href="https://colab.research.google.com/github/Pragya1712/Machine-Learning-Hand-Code/blob/main/Softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
import logging

In [ ]:
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)


In [ ]:
# define softmax function
def softmax(z):
  ez = np.exp(z-np.max(z)) # prevent overflow
  return ez/np.sum(ez)

In [ ]:
# Create 4 classes data centres
centres = [[-5,2],[-2,-2],[1,2],[5,-2]]
X_train,y_train = make_blobs(
    n_samples = 2000,
    centers = centres,
    cluster_std = 1.0,
    random_state=30
)


In [ ]:
# Softmax activation in last layer (not preferred)
model = Sequential([
    Dense(units=25,activation='relu',input_shape=(2,),name="L1"),
    Dense(units=15,activation='relu',name="L2"),
    Dense(units=4,activation='softmax',name="L3"),
])
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

In [ ]:
model.fit(X_train,y_train,epochs=20,verbose=1)

Epoch 1/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0323
Epoch 2/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0274
Epoch 3/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0244
Epoch 4/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0228
Epoch 5/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0234
Epoch 6/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0277
Epoch 7/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0253
Epoch 8/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0232
Epoch 9/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0223
Epoch 10/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0246
Epoch 11/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0199
Epoch 12/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0196
Epoch 13/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0181
Epoch 14/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0210
Epoch 15/20
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0174
Epoch 16/20
63/63 ━

In [ ]:
p_nonpreferred = model.predict(X_train)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [ ]:
print(p_nonpreferred[:4])

[[1.8537201e-05 6.4375963e-05 9.9930215e-01 6.1505678e-04]
 [9.9964702e-01 3.5206976e-04 9.2437494e-07 2.4734511e-08]
 [9.9233025e-01 7.6303822e-03 3.7035505e-05 2.3198681e-06]
 [2.4272499e-04 9.9845260e-01 9.1816421e-04 3.8651901e-04]]


In [ ]:
print("largest value: ",np.max(p_nonpreferred))
print("smallest value: ", np.min(p_nonpreferred))

largest value:  0.99999994
smallest value:  1.0609714e-15


In [ ]:
# using from_logits = True (preferred)
p_model = Sequential([
    Dense(units=25,activation='relu',name="L1"),
    Dense(units=15,activation='relu',name="L2"),
    Dense(units=4,activation='linear',name="L3"),
])
p_model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.001)
)


In [ ]:
p_model.fit(X_train,y_train,epochs=10,verbose=1)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.2549
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5780
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2570
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1209
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0738
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0650
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0540
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0449
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0449
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0367


In [ ]:
p_preferred = model.predict(X_train)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [ ]:
print(p_preferred[:4])

[[1.8537201e-05 6.4375963e-05 9.9930215e-01 6.1505678e-04]
 [9.9964702e-01 3.5206976e-04 9.2437494e-07 2.4734511e-08]
 [9.9233025e-01 7.6303822e-03 3.7035505e-05 2.3198681e-06]
 [2.4272499e-04 9.9845260e-01 9.1816421e-04 3.8651901e-04]]


In [ ]:
print("largest value: ",np.max(p_preferred))
print("smallest value: ", np.min(p_preferred))

largest value:  0.99999994
smallest value:  1.0609714e-15


In [ ]:
# Apply softmax to get the probabilities
sm_preferred = tf.nn.softmax(p_preferred).numpy()

In [ ]:
print(sm_preferred[:2])


[[0.1749176  0.17492561 0.47513482 0.17502198]
 [0.4752495  0.17495783 0.1748964  0.17489626]]


In [ ]:
print("largest value:", np.max(sm_preferred),
      "smallest value:", np.min(sm_preferred))


largest value: 0.4753669 smallest value: 0.17487769


In [ ]:
# Final prediction(Class prediction)
print("Predicted classes for first 5 samples")
for i in range(5):
  print(f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

Predicted classes for first 5 samples
[1.8537201e-05 6.4375963e-05 9.9930215e-01 6.1505678e-04], category: 2
[9.9964702e-01 3.5206976e-04 9.2437494e-07 2.4734511e-08], category: 0
[9.9233025e-01 7.6303822e-03 3.7035505e-05 2.3198681e-06], category: 0
[2.4272499e-04 9.9845260e-01 9.1816421e-04 3.8651901e-04], category: 1
[4.5140277e-04 3.3099921e-05 9.9946344e-01 5.2147880e-05], category: 2
